export default function TermsContent() {
  return (
    <div className="font-sans text-sm text-zinc-300 space-y-6">
      <div className="text-center space-y-1 pb-4 border-b border-border">
        <p className="text-foreground font-semibold text-base">JUPITER TECH LTD</p>
        <p className="text-zinc-400 text-xs">AI-Powered News &amp; Content Engine for CFD Brokers</p>
        <p className="text-foreground font-semibold mt-2">TERMS AND CONDITIONS OF USE</p>
        <p className="text-zinc-400 text-xs">FOR CFD BROKER CLIENTS AND AUTHORISED USERS</p>
        <div className="flex items-center justify-center gap-3 mt-2 text-[11px] text-zinc-500">
          <span>Effective Date: 23 March 2026</span>
          <span>·</span>
          <span>Version 3.0</span>
          <span>·</span>
          <span>Governing Law: England and Wales</span>
        </div>
      </div>

      {/* TABLE OF CONTENTS */}
      <div className="space-y-1">
        <h2 className="text-foreground font-semibold">TABLE OF CONTENTS</h2>
        <ol className="list-decimal list-inside text-zinc-400 text-xs space-y-0.5">
          <li>Definitions and Interpretation</li>
          <li>Platform Description and Fundamental Acknowledgements</li>
          <li>Client Obligations and Regulatory Compliance</li>
          <li>Limitation of Liability and Indemnification</li>
          <li>Intellectual Property</li>
          <li>Data Protection and Privacy</li>
          <li>Disclaimers and Warranties</li>
          <li>Prohibited Uses</li>
          <li>Access and Future Fees</li>
          <li>Term and Termination</li>
          <li>Governing Law and Dispute Resolution</li>
          <li>Force Majeure</li>
          <li>General Provisions</li>
          <li>Acknowledgement and Acceptance</li>
        </ol>
      </div>

      {/* 1. DEFINITIONS AND INTERPRETATION */}
      <div className="space-y-3">
        <h2 className="text-foreground font-semibold">1. DEFINITIONS AND INTERPRETATION</h2>
        <p className="text-xs text-zinc-400 font-semibold">1.1 Definitions</p>
        <p className="leading-relaxed">In these Terms and Conditions, unless the context indicates otherwise, the following words and expressions shall bear the meanings assigned to them:</p>
        <p className="leading-relaxed"><strong>&quot;Applicable Law&quot;</strong> means all laws, statutes, regulations, rules, directives, guidelines, guidance notes, codes of practice, and regulatory requirements applicable to the Client in any jurisdiction in which the Client operates or to which its activities are directed, including without limitation the Financial Services and Markets Act 2000, the Financial Conduct Authority Handbook, MiFID II (Directive 2014/65/EU) and MiFIR (Regulation 600/2014), CySEC Directives, ASIC Regulatory Guides, ESMA guidelines, the Market Abuse Regulation (EU MAR), the UK General Data Protection Regulation, the Data Protection Act 2018, the Consumer Rights Act 2015, the Unfair Contract Terms Act 1977, and any equivalent legislation in any other jurisdiction, as amended from time to time.</p>
        <p className="leading-relaxed"><strong>&quot;Authorised User&quot;</strong> means any individual to whom the Client has granted access to the Platform via the invitation mechanism, including employees, contractors, and agents of the Client.</p>
        <p className="leading-relaxed"><strong>&quot;CFD&quot;</strong> means a Contract for Difference, being a derivative financial instrument that allows parties to speculate on price movements of underlying assets without owning the underlying asset.</p>
        <p className="leading-relaxed"><strong>&quot;CFD Broker&quot;</strong> or <strong>&quot;Client&quot;</strong> or <strong>&quot;You&quot;</strong> means the entity that enters into an agreement with Jupiter Tech to access and use the Platform, being a firm that is licensed, registered, or otherwise authorised under Applicable Law to offer, market, distribute, or facilitate the trading of CFDs or other derivative financial instruments.</p>
        <p className="leading-relaxed"><strong>&quot;Chat Interface&quot;</strong> means the browser-based conversational interface through which Authorised Users submit prompts to the AI Engine and receive Outputs.</p>
        <p className="leading-relaxed"><strong>&quot;Content&quot;</strong> or <strong>&quot;Output&quot;</strong> means any and all text generated by the AI Engine in response to an Authorised User&apos;s prompt, including without limitation market briefs, social media posts, risk alerts, market wrap-ups, crisis response communications, currency pair analyses, and any other text-based material, in whatever form or format, including plain text and markdown.</p>
        <p className="leading-relaxed"><strong>&quot;Data Sources&quot;</strong> means the publicly available third-party information sources from which the Platform aggregates data to provide context to the AI Engine, including: (i) news articles sourced via RSS feeds from third-party publishers; (ii) market price data sourced from the Yahoo Finance API; and (iii) economic calendar data sourced from Fair Economy. The specific sources may change from time to time at Jupiter Tech&apos;s sole discretion.</p>
        <p className="leading-relaxed"><strong>&quot;Derived Content&quot;</strong> means any content, material, communication, or publication created, adapted, modified, or otherwise derived by the Client or any Authorised User from or using any Output, whether in whole or in part.</p>
        <p className="leading-relaxed"><strong>&quot;Financial Promotion&quot;</strong> means any invitation or inducement to engage in investment activity within the meaning of section 21 of the Financial Services and Markets Act 2000, or any equivalent concept under any other Applicable Law.</p>
        <p className="leading-relaxed"><strong>&quot;AI Engine&quot;</strong> means the third-party large language model (currently Anthropic Claude) that generates Outputs based on the Authorised User&apos;s prompts and the contextual data provided by the Platform. The AI Engine is a third-party service and Jupiter Tech does not own, control, or develop the underlying AI model.</p>
        <p className="leading-relaxed"><strong>&quot;Intellectual Property Rights&quot;</strong> means all patents, copyrights, trade marks, design rights, database rights, rights in know-how, trade secrets, and all other intellectual property rights of any nature, whether registered or unregistered, anywhere in the world.</p>
        <p className="leading-relaxed"><strong>&quot;Jupiter Tech&quot;</strong>, <strong>&quot;We&quot;</strong>, <strong>&quot;Us&quot;</strong>, or <strong>&quot;Our&quot;</strong> means Jupiter Tech Ltd, a company incorporated under the laws of England and Wales, including its directors, officers, employees, agents, affiliates, subsidiaries, successors, and assigns.</p>
        <p className="leading-relaxed"><strong>&quot;Platform&quot;</strong> means the browser-based SaaS application operated by Jupiter Tech at its designated URL, comprising the Chat Interface, the data aggregation layer, the integration with the AI Engine, and all associated software, including any updates, upgrades, or modifications.</p>
        <p className="leading-relaxed"><strong>&quot;Quick Actions&quot;</strong> means the pre-configured prompt templates available within the Platform (such as Morning Market Brief, Social Media Post, Risk Alert, Weekly Market Wrap, Crisis Response, Currency Pair Deep Dive, and Weekend Prep), which may be modified by Jupiter Tech from time to time.</p>
        <p className="leading-relaxed"><strong>&quot;Regulatory Authority&quot;</strong> means any governmental, statutory, regulatory, or self-regulatory body with jurisdiction over the Client, including without limitation the FCA, CySEC, ASIC, ESMA, FSCA, and any equivalent body in any other jurisdiction.</p>
        <p className="leading-relaxed"><strong>&quot;Access Period&quot;</strong> means the period during which the Client is granted access to the Platform, commencing on the date of the Client&apos;s first login and continuing until terminated in accordance with Clause 10. Access is currently provided free of charge. Jupiter Tech reserves the right to introduce fees upon thirty (30) days&apos; written notice.</p>

        <p className="text-xs text-zinc-400 font-semibold mt-4">1.2 Interpretation</p>
        <p className="leading-relaxed">References to clauses and schedules are to clauses of, and schedules to, these Terms and Conditions unless otherwise stated. Headings are for convenience only. Words importing the singular include the plural and vice versa. The words &quot;include&quot;, &quot;includes&quot;, and &quot;including&quot; shall be deemed to be followed by &quot;without limitation&quot;.</p>
      </div>

      {/* 2. PLATFORM DESCRIPTION */}
      <div className="space-y-3">
        <h2 className="text-foreground font-semibold">2. PLATFORM DESCRIPTION AND FUNDAMENTAL ACKNOWLEDGEMENTS</h2>
        <p className="text-xs text-zinc-400 font-semibold">2.1 What the Platform Does</p>
        <p className="leading-relaxed">The Platform is a browser-based software tool that aggregates publicly available market data, news, and economic calendar information from the Data Sources, provides this information as context to the AI Engine, and enables Authorised Users to generate text-based content through the Chat Interface by submitting natural language prompts.</p>

        <p className="text-xs text-zinc-400 font-semibold">2.2 What the Platform Does Not Do</p>
        <p className="leading-relaxed">The Client expressly acknowledges and agrees that the Platform:</p>
        <ul className="list-disc list-inside space-y-1 text-zinc-400 text-xs leading-relaxed ml-2">
          <li>Does not publish, distribute, or transmit any Output to any third party or channel;</li>
          <li>Does not integrate with any downstream system, CMS, email platform, or social media API;</li>
          <li>Does not provide financial advice, investment advice, trading signals, or personal recommendations;</li>
          <li>Does not perform the function of investment research as defined under MiFID II or the FCA Handbook;</li>
          <li>Does not approve, verify, or fact-check any Output;</li>
          <li>Does not access, collect, or process any personal data of the Client&apos;s end customers;</li>
          <li>Does not guarantee the inclusion of any specific risk warning or disclaimer in any Output;</li>
          <li>Does not provide real-time market data — prices may be delayed, stale, or inaccurate; and</li>
          <li>Does not constitute a regulated financial service or data feed.</li>
        </ul>

        <p className="text-xs text-zinc-400 font-semibold">2.3 AI-Generated Content — Fundamental Limitations</p>
        <p className="leading-relaxed font-semibold text-zinc-200">THE CLIENT AND EACH AUTHORISED USER EXPRESSLY ACKNOWLEDGE AND ACCEPT THAT:</p>
        <ul className="list-disc list-inside space-y-1 text-zinc-400 text-xs leading-relaxed ml-2">
          <li>All Outputs are generated by a third-party large language model. Jupiter Tech does not employ human editors or reviewers;</li>
          <li>Large language models may produce factual errors, fabrications, hallucinations, and misleading statements;</li>
          <li>The AI Engine may produce different Outputs from identical prompts at different times;</li>
          <li>Data Sources are free, publicly available, third-party services with no guaranteed accuracy;</li>
          <li>News articles are refreshed periodically (not in real time) with no SLA on freshness;</li>
          <li>All Outputs constitute raw, unverified, draft material intended solely as a starting point for the Client&apos;s own review processes; and</li>
          <li>Prompt-level instructions for risk disclaimers and source citations are not code-enforced guarantees.</li>
        </ul>

        <p className="text-xs text-zinc-400 font-semibold">2.4 Technology Provider — Not a Financial Services Provider</p>
        <p className="leading-relaxed">Jupiter Tech is a technology company. It is not authorised, regulated, or licensed by the FCA or any other Regulatory Authority. The Platform is a productivity tool for the Client&apos;s staff.</p>
      </div>

      {/* 3. CLIENT OBLIGATIONS */}
      <div className="space-y-3">
        <h2 className="text-foreground font-semibold">3. CLIENT OBLIGATIONS AND REGULATORY COMPLIANCE</h2>
        <p className="text-xs text-zinc-400 font-semibold">3.1 Sole Regulatory Responsibility</p>
        <p className="leading-relaxed font-semibold text-zinc-200">THE CLIENT IS SOLELY AND EXCLUSIVELY RESPONSIBLE FOR ENSURING THAT ANY USE, ADAPTATION, PUBLICATION, DISTRIBUTION, OR COMMUNICATION OF ANY OUTPUT OR DERIVED CONTENT COMPLIES WITH ALL APPLICABLE LAW.</p>

        <p className="text-xs text-zinc-400 font-semibold">3.2 The Copy-to-Clipboard Boundary</p>
        <p className="leading-relaxed">The boundary of Jupiter Tech&apos;s responsibility ends at the point at which an Output is displayed in the Chat Interface. The moment an Authorised User copies any Output, responsibility transfers entirely and irrevocably to the Client.</p>

        <p className="text-xs text-zinc-400 font-semibold">3.3 CFD-Specific Regulatory Obligations</p>
        <p className="leading-relaxed">The Client is solely responsible for compliance with MiFID II, MiFIR, FCA Handbook (COBS, SYSC, PROD), CySEC Circulars, ASIC Regulatory Guides, all mandatory risk warnings, fair/clear/not misleading requirements, Market Abuse Regulation, product governance obligations, data protection legislation, and any other applicable regulatory requirement.</p>

        <p className="text-xs text-zinc-400 font-semibold">3.4 Mandatory Pre-Publication Review</p>
        <p className="leading-relaxed">The Client shall implement and maintain a documented pre-publication review process including: factual verification, compliance review, legal review, insertion of mandatory risk warnings, market integrity checks, editorial review, and sign-off by a qualified individual.</p>

        <p className="text-xs text-zinc-400 font-semibold">3.5 Non-Delegation of Regulatory Responsibility</p>
        <p className="leading-relaxed">Under MiFID II, the FCA Handbook, and equivalent outsourcing rules, a regulated firm that outsources operational functions remains fully responsible for all regulatory obligations. The Client&apos;s use of the Platform does not transfer any regulatory obligation to Jupiter Tech.</p>

        <p className="text-xs text-zinc-400 font-semibold">3.6 Client Representations and Warranties</p>
        <p className="leading-relaxed">By accessing the Platform, the Client represents that it holds all required licences, has qualified compliance and legal personnel, will not publish unreviewed Outputs, will not attribute Outputs to Jupiter Tech, and will ensure all Authorised Users are bound by these Terms.</p>

        <p className="text-xs text-zinc-400 font-semibold">3.7 Record-Keeping</p>
        <p className="leading-relaxed">The Client shall maintain complete records of all Outputs, modifications, reviews, and approvals for a minimum of seven (7) years. The Client shall not rely solely on Jupiter Tech&apos;s storage for regulatory record-keeping.</p>
      </div>

      {/* 4. LIMITATION OF LIABILITY */}
      <div className="space-y-3">
        <h2 className="text-foreground font-semibold">4. LIMITATION OF LIABILITY AND INDEMNIFICATION</h2>
        <p className="text-xs text-zinc-400 font-semibold">4.2 Unlimited Liability</p>
        <p className="leading-relaxed">Nothing in these Terms shall limit liability for death or personal injury caused by negligence, fraud or fraudulent misrepresentation, wilful misconduct, or any liability that cannot be excluded under English law.</p>

        <p className="text-xs text-zinc-400 font-semibold">4.3 Exclusion of Indirect and Consequential Loss</p>
        <p className="leading-relaxed">Neither party shall be liable for loss of profits, revenue, business, goodwill, data, or any indirect, special, or consequential loss. This includes any regulatory fine, penalty, or enforcement action imposed on the Client in connection with its use of any Output.</p>

        <p className="text-xs text-zinc-400 font-semibold">4.4 Cap on Direct Liability</p>
        <p className="leading-relaxed">Jupiter Tech&apos;s total aggregate liability shall not exceed one hundred pounds sterling (&pound;100), reflecting that the Platform is currently provided free of charge. If fees are introduced, the cap shall increase to the greater of total fees paid in the preceding 12 months or &pound;100.</p>

        <p className="text-xs text-zinc-400 font-semibold">4.5 Indemnification by the Client</p>
        <p className="leading-relaxed">The Client shall indemnify Jupiter Tech against any losses, damages, costs, claims, fines, or penalties arising from: use or publication of any Output, breach of these Terms, breach of Applicable Law, regulatory proceedings, third-party claims, IP infringement from modified Outputs, data protection violations, or any allegation that Jupiter Tech is carrying on a regulated activity.</p>
      </div>

      {/* 5. INTELLECTUAL PROPERTY */}
      <div className="space-y-3">
        <h2 className="text-foreground font-semibold">5. INTELLECTUAL PROPERTY</h2>
        <p className="leading-relaxed">All IP rights in the Platform remain with Jupiter Tech. The Client receives a non-exclusive, non-transferable, non-sublicensable, revocable licence to use, modify, and publish Outputs solely for its own business purposes. The Client shall not attribute any Output to Jupiter Tech. The Client is responsible for ensuring its use of Outputs does not infringe third-party IP.</p>
      </div>

      {/* 6. DATA PROTECTION */}
      <div className="space-y-3">
        <h2 className="text-foreground font-semibold">6. DATA PROTECTION AND PRIVACY</h2>
        <p className="leading-relaxed">The Platform processes: (i) email addresses for authentication; (ii) chat history for service delivery; and (iii) usage metrics. No end-customer personal data is collected. Jupiter Tech acts as data processor; the Client is data controller. Sub-processors include Supabase (database, SOC 2), Vercel (hosting), and Anthropic (AI Engine). Chat prompts and Outputs are not shared with the AI provider for model training unless separately consented.</p>
      </div>

      {/* 7. DISCLAIMERS */}
      <div className="space-y-3">
        <h2 className="text-foreground font-semibold">7. DISCLAIMERS AND WARRANTIES</h2>
        <p className="leading-relaxed">The Platform and all Outputs are provided &quot;as is&quot; and &quot;as available&quot;. Jupiter Tech disclaims all warranties not expressly stated. No warranty is made that any Output will comply with any Applicable Law or contain appropriate risk warnings. Jupiter Tech shall have no liability for failures of third-party services (AI Engine, Data Sources, hosting).</p>
      </div>

      {/* 8. PROHIBITED USES */}
      <div className="space-y-3">
        <h2 className="text-foreground font-semibold">8. PROHIBITED USES</h2>
        <p className="leading-relaxed">The Client shall not: generate content to manipulate markets or facilitate insider dealing; publish Outputs without mandatory risk warnings; represent that Jupiter Tech authored or endorsed any Output; use the Platform to generate misleading Financial Promotions; reverse-engineer the Platform; circumvent access controls; overburden or impair the Platform; sublicense or resell access; submit harmful prompts; or violate Applicable Law.</p>
      </div>

      {/* 9. ACCESS AND FEES */}
      <div className="space-y-3">
        <h2 className="text-foreground font-semibold">9. ACCESS AND FUTURE FEES</h2>
        <p className="leading-relaxed">Access is currently provided free of charge. Jupiter Tech may introduce fees upon thirty (30) days&apos; written notice. Continued use after the fee commencement date constitutes acceptance. If the Client does not wish to accept fees, its sole remedy is to cease using the Platform.</p>
      </div>

      {/* 10. TERMINATION */}
      <div className="space-y-3">
        <h2 className="text-foreground font-semibold">10. TERM AND TERMINATION</h2>
        <p className="leading-relaxed">Either party may terminate for material breach (with 14-day cure period), insolvency, or regulatory action. Jupiter Tech may terminate immediately for Applicable Law violations. Either party may terminate for convenience with 14 days&apos; notice. Upon termination, all licences cease and Jupiter Tech may delete data after 30 days. Clauses 1-8, 11-13 survive termination.</p>
      </div>

      {/* 11. GOVERNING LAW */}
      <div className="space-y-3">
        <h2 className="text-foreground font-semibold">11. GOVERNING LAW AND DISPUTE RESOLUTION</h2>
        <p className="leading-relaxed">Governed by the laws of England and Wales. Exclusive jurisdiction of the courts of England and Wales. Before court proceedings, parties shall negotiate in good faith for 30 days, then mediation under CEDR. Court proceedings may commence after 60 days from mediator appointment.</p>
      </div>

      {/* 12. FORCE MAJEURE */}
      <div className="space-y-3">
        <h2 className="text-foreground font-semibold">12. FORCE MAJEURE</h2>
        <p className="leading-relaxed">Neither party shall be liable for failures caused by circumstances beyond reasonable control. If a force majeure event continues for more than ninety (90) days, either party may terminate on written notice.</p>
      </div>

      {/* 13. GENERAL PROVISIONS */}
      <div className="space-y-3">
        <h2 className="text-foreground font-semibold">13. GENERAL PROVISIONS</h2>
        <p className="leading-relaxed">These Terms constitute the entire agreement. Jupiter Tech may amend with 30 days&apos; notice; continued use constitutes acceptance. Invalid provisions shall be severed. No waiver by failure to exercise rights. Client may not assign without consent. No third-party rights except for Indemnified Parties under Clause 4.5. Notices by email. Parties are independent contractors.</p>
      </div>

      {/* 14. ACKNOWLEDGEMENT */}
      <div className="space-y-3">
        <h2 className="text-foreground font-semibold">14. ACKNOWLEDGEMENT AND ACCEPTANCE</h2>
        <p className="leading-relaxed font-semibold text-zinc-200">BY SELECTING THE ACCEPTANCE CHECKBOX, THE CLIENT AND EACH AUTHORISED USER ACKNOWLEDGES AND AGREES THAT:</p>
        <ul className="list-disc list-inside space-y-1 text-zinc-400 text-xs leading-relaxed ml-2">
          <li>They have read, understood, and agree to be bound by these Terms;</li>
          <li>Jupiter Tech is a technology provider, not a financial services provider;</li>
          <li>All Outputs are AI-generated, unverified, and constitute raw draft material only;</li>
          <li>The Platform has no publishing or distribution capability;</li>
          <li>The AI Engine may hallucinate or generate inaccurate content;</li>
          <li>Market data may be delayed, stale, or inaccurate;</li>
          <li>No Output contains a programmatically guaranteed risk warning;</li>
          <li>The Client bears sole responsibility for all regulatory compliance;</li>
          <li>The liability and indemnification provisions are reasonable;</li>
          <li>The Client has been afforded the opportunity to seek independent legal advice; and</li>
          <li>Regulatory compliance obligations cannot be delegated to Jupiter Tech.</li>
        </ul>
      </div>

      <div className="text-center pt-4 border-t border-border space-y-1">
        <p className="text-zinc-500 text-xs">— END OF TERMS AND CONDITIONS —</p>
        <p className="text-zinc-600 text-[11px]">Jupiter Tech Ltd · Registered in England and Wales</p>
        <p className="text-zinc-600 text-[11px]">Accepted electronically. No physical signature required.</p>
      </div>
    </div>
  );
}
